[package]
name = "rustboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libspa-sys = "0.8.0"
pipewire = "0.8.0"
rodio = "0.19.0"
